HP-278
handle-fi/handle-subgraph pull request #2
Opened 2021-05-06 22:58 UTC by rellfy

Adds a mapping module to index fxKeeperPool data

2021-05-06 23:00 UTC, bitcoinbrisbane commented on src/mappings/fxKeeperPool.ts
> +  if (poolCollateral == null) {
Should this be
```suggestion
  if (poolCollateral === null) {
```

2021-05-06 23:02 UTC, rellfy commented on src/mappings/fxKeeperPool.ts
> +  if (poolCollateral == null) {
`==` covers both `null` and `undefined`, so I prefer to use that when checking for null values otherwise two conditions would be needed

2021-05-06 23:02 UTC, bitcoinbrisbane requested changes
One small thing.

2021-05-06 23:09 UTC, bitcoinbrisbane approved these changes
LGTM

2021-05-07 00:30 UTC, Mitchell139 approved these changes

2021-05-07 00:30 UTC, merged