HP-469
handle-fi/handle-subgraph pull request #6
Opened 2021-06-23 00:22 UTC by rellfy

Indexes redeemable fxToken amounts in the Vault entity

2021-06-23 00:24 UTC, xiangzhe0812 approved these changes

2021-06-23 00:50 UTC, ahinchliff approved these changes

2021-06-23 07:25 UTC, Mitchell139 requested changes
```{
  "errors": [
    {
      "locations": [
        {
          "column": 5,
          "line": 8
        }
      ],
      "message": "Type `Vault` has no field `redeemableTokens`"
    }
  ]
}
```

2021-06-23 08:51 UTC, rellfy commented
@Mitchell139 I just realised that's because I deployed #7 which wasn't merged with this, so only the changes from that branch applied. I'll merge them together and deploy that so that both branches are live.

2021-06-24 00:45 UTC, Mitchell139 approved these changes

2021-06-24 00:45 UTC, merged